### ISSUE TITLE
Update Readme with Instructions / Sample Config

### ISSUE THREAD

**Issue by Handfish** [joshlgrossman/better#1]
Hi.
I've been doing some reading about front-end solutions and stumbled upon your app-starter and this repo. I'd love to see it running properly, but the config.js file has been included in the .gitignore and consequentially the application does not build.

I've gotten this far:
Created config.js in /src/server
export let jwtSecret = 'test12345';
export let mongoDb = 'mongodb://localhost:27017/sampleDB';

npm run-script build

Started mongod, node ./dist/server/index.js, http-server ./dist/client/
Now when I hit register user I get in the chrome console:
"Failed to load resource: the server responded with a status of 405 (Method Not Allowed)"

This is almost certainly a server configuration issue, but I am not certain how to fix this. I would appreciate any help.

**Comment by joshlgrossman** [comment]
The `config.js` file also needs a port to run the server on.

`export let port = 8000;`

For development purposes, the server is also set up to server static files from the `./dist/client` directory.  You should be able to simply run:

`npm start` 

which builds the client and starts the server. Please let me know if that doesn't work.

**Comment by Handfish** [comment]
Got it running. Thanks for the help.
